### ISSUE TITLE
Subscription missing in v1.1.0

### ISSUE THREAD

**Issue by devyg** [yogiben/meteor-admin#124] opened 2015-01-28 22:52 UTC
The list generation of created objects seems to be broken with v1.1.0. I have the message "There are no visible items in this collection.". Manually subscribing to the collections makes the objects appear. 
Maybe the subscription to 'adminCollection' is missing somewhere. It is only present for "new" or "edit" paths. Or am I missing something ?

**Comment by theduke** [comment] 2015-01-29 23:09
Same issue here!

**Comment by backjo** [comment] 2015-02-03 01:54
Same here!

**Comment by marekrogala** [comment] 2015-02-05 10:34
+1

**Comment by theduke** [comment] 2015-02-05 12:19
I have downgraded for now, I hope a fix will come soon.
There should probably be tests for this stuff. ^^

**Comment by taromero** [comment] 2015-02-09 05:45
+1 for a fix for this one.

**Comment by obiwarn** [comment] 2015-02-10 14:17
downgrade works like a charm.

to save you the time:

meteor remove yogiben:admin
meteor add yogiben:admin@=1.0.9

**Comment by devyg** [comment] 2015-02-10 14:37
Indeed it does. But a fix would be better :D

**Comment by taromero** [comment] 2015-02-11 05:42
I published a package with a patch for 1.1.0: https://atmospherejs.com/canotto90/admin-1.1.0-patch. Check it out if you want to try 1.1.0 while they fix the subscriptions issue.

I fix this by removing lines 68&69 from startup.coffee.

**Comment by theduke** [comment] 2015-02-11 06:13
Seems like the package author is refactoring to use aldeed:tabular instead of meteor-pages, so it will  be fixed once that is done.

Shame that he seems short on time and does not maintain admin well.

**Comment by taromero** [comment] 2015-02-11 12:55
@devyg when you say "manually subscribing", how do you do that? what publication do you subscribe to to make it work? Thanks.

**Comment by devyg** [comment] 2015-02-11 15:42
@taromero 
I just created some publications for each of my objects collections and then subscribed to it in a 'onBeforeAction' in the router configuration. I first did that so I could continue to work despite the bug.
This is very ugly and kind of like using the autopublish package.

**Comment by Firfi** [comment] 2015-02-17 04:25
Subscribing. Would be great to have fix for the latest version.

**Comment by vbezruchkin** [comment] 2015-02-22 14:19
Hey guys, the same issue with the default version. 
Any ETA for this from the official developer? I am absolutely sure @yogiben is busy with the projects, but a quick official solution would be appreciated much. 
Thanks in advance.

**Comment by p4bloch** [comment] 2015-03-13 01:40
Same problem here. I'm new to this tool and I've been scratching my head *really* hard with this bug. God bless OSS and active communities like this one that report this kind of bugs :)
Hoping @yogiben can find the time to fix this one in the official package soon enough. Thanks!

**Comment by rwatts3** [comment] 2015-03-14 23:17
Bump ! 
I must say that I am surprised that it has taken this long to get a reply from this issue.

**Comment by rwatts3** [comment] 2015-03-14 23:17
I will look into this issue and submit a PR.

**Comment by lyricalpolymath** [comment] 2015-03-17 16:27
Hi everyone. I found a hack that fixes the problem.
probably the bug is caused by the existence of more than one publication for a collection, so that the admin dashboard doesn't know which subscription to pick.
example:
```
Carts = new Mongo.Collection('carts');

// in server code
Meteor.publish('carts', function(){

} )

**Comment by lyricalpolymath** [comment] 2015-03-17 16:42
Hi everyone. I found a hack that fixes the problem, until @yogiben creates a permanent feature/solution for this bug.

## problem
probably the bug is caused by the **existence of more than one publication for a collection**, so that the admin dashboard doesn't know which subscription to pick.
example:
```
Posts = new Mongo.Collection('posts');

// in server code 
// publish all posts
Meteor.publish('posts', function(){
    return Posts.find();
} )
// publishing only one post
Meteor.publish('singlePost', function(postId) {
   return Posts.find({_id: postId});
})
```

## temporary solution
so the solution is to [hook](https://github.com/iron-meteor/iron-router/blob/devel/Guide.md#applying-hooks-to-specific-routes) onto the the route and add the desired subscription there.
So simply add something like this to your routes

```
Router.waitOn(function(){
    console.log('----------ROUTER waitOn subscriptions for admin'); // this is to verify in the console that this function is actually called > you can delete it after it's working
    return Meteor.subscribe('posts') // put here the subscription to all documents
}, {
    only: ['adminDashboard'] // this is the name of the yogiben:admin route
});
```

**remember to change the subscription `posts` to the one you are having problems with.**

## proposed definitive solution
@yogiben should add a `subscription` property to the collection object in the `AdminConfig`.
something like this:
```
AdminConfig = {
  collections: {
    Posts: {
       subscription: 'posts',
       tableColumns: [ ... ],
       ....
    }
  }
```

**Comment by p4bloch** [comment] 2015-03-18 00:22
+1 for @lyricalpolymath's solution

**Comment by MindBlowStudio** [comment] 2015-04-12 23:54
ty @lyricalpolymath  works perfect =D

**Comment by yogiben** [comment] 2015-05-01 07:36
Sorry for the delay (we're working on a new version).

**Comment by mpowaga** [comment] 2015-05-12 01:47
Solved in 1.1.1.

**Closed by mpowaga** 2015-05-12 01:47 UTC

**Comment by HazemKhaled** [comment] 2015-05-13 13:43
@mpowaga still not working with 1.1.1

**Comment by pozylon** [comment] 2015-05-21 07:11
not working... tried auxCollections as well as auto form's "collection" property in the scheme...

`  groupAllocation:
    type: String
    optional: true
    regEx: SimpleSchema.RegEx.Id
    autoform:
      afFieldInput:
        collection: 'Groups'
        options: ->
          groups = Groups.find({}).fetch()
          _.map groups, (group)->
            label: group.name
            value: group._id`

adminConfig:

`		Children: {
			color: 'green'
			icon: 'child'
			extraFields: ['birthday']
			auxCollections: ['Attachments','Groups']
			tableColumns: [
				{label: 'Firstname', name: 'firstName'}
				{label: 'Surname', name: 'lastName'}
				{label: 'Birthday', name: 'formattedBirthday()'}
			]
		}`
